# Generated by Django 3.0.6 on 2020-05-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userinfo_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
