# Generated by Django 3.0.6 on 2020-05-26 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200526_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taking',
            name='book',
        ),
        migrations.RemoveField(
            model_name='taking',
            name='taken_by',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Taking',
        ),
    ]
