# Generated by Django 3.0.6 on 2020-05-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200526_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='hide_email2',
            field=models.BooleanField(default=True),
        ),
    ]
