# Generated by Django 3.0.6 on 2020-05-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userinfo_hide_email2'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
