# Generated by Django 3.0.6 on 2020-05-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200527_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
