# Generated by Django 3.0.6 on 2020-05-20 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('publisher', models.CharField(max_length=500)),
                ('authors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Author')),
            ],
        ),
    ]
