# Generated by Django 3.0.6 on 2020-05-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200526_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copies_available',
            field=models.IntegerField(default=1),
        ),
    ]
