# Generated by Django 3.0.6 on 2020-05-26 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_copies_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_by', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='taking',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_by', to='books.Book'),
        ),
    ]
