# Generated by Django 3.0.6 on 2020-05-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='digital',
            field=models.FileField(blank=True, null=True, upload_to='digital_books/'),
        ),
    ]
